site_name: {{cookiecutter.project_name}}
site_description: {{cookiecutter.project_short_description}}
repo_url: {% if cookiecutter.ci_platform == "github" %}https://github.com/{{cookiecutter.repository_owner}}/{{cookiecutter.project_dir}}{% else %}https://gitlab.com/{{cookiecutter.repository_owner}}/{{cookiecutter.project_dir}}{% endif %}
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
nav:
  - Home: index.md
  - API: api/index.md
